# Generated by Django 3.2.9 on 2021-11-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Userid', models.CharField(max_length=64, verbose_name='아이디')),
                ('Password', models.CharField(max_length=64, verbose_name='비밀번호')),
                ('Nickname', models.CharField(max_length=64, verbose_name='닉네임')),
                ('Username', models.CharField(max_length=64, verbose_name='이름')),
                ('phonenumber', models.CharField(max_length=64, verbose_name='휴대폰번호')),
                ('registered', models.DateTimeField(auto_now_add=True, verbose_name='등록')),
            ],
        ),
    ]
